// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQdzKFTsDMOf38g7Soy66mLrux7Ugkwi0',
    appId: '1:599148167888:web:76fd4fc5f1a9771a17d4d5',
    messagingSenderId: '599148167888',
    projectId: 'clevertap-test-app',
    authDomain: 'clevertap-test-app.firebaseapp.com',
    storageBucket: 'clevertap-test-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhqRg3R_JQ23WJK-mTcK3n1ePO3PKj1Y8',
    appId: '1:599148167888:ios:ff4da956d414cb7117d4d5',
    messagingSenderId: '599148167888',
    projectId: 'clevertap-test-app',
    storageBucket: 'clevertap-test-app.firebasestorage.app',
    iosBundleId: 'com.example.sportss',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhqRg3R_JQ23WJK-mTcK3n1ePO3PKj1Y8',
    appId: '1:599148167888:ios:33f2c34c22ed536417d4d5',
    messagingSenderId: '599148167888',
    projectId: 'clevertap-test-app',
    storageBucket: 'clevertap-test-app.firebasestorage.app',
    iosBundleId: 'com.example.sport',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQdzKFTsDMOf38g7Soy66mLrux7Ugkwi0',
    appId: '1:599148167888:web:76fd4fc5f1a9771a17d4d5',
    messagingSenderId: '599148167888',
    projectId: 'clevertap-test-app',
    authDomain: 'clevertap-test-app.firebaseapp.com',
    storageBucket: 'clevertap-test-app.firebasestorage.app',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKbR4bC8qzmdhynYM2NszuOC0kFIR3xOo',
    appId: '1:599148167888:android:4bd421db910422de17d4d5',
    messagingSenderId: '599148167888',
    projectId: 'clevertap-test-app',
    storageBucket: 'clevertap-test-app.firebasestorage.app',
  );
}
